### ISSUE TITLE
Y-axis label should Include min, max values and not block the waveform image

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#17]
The waveform graph doesn't include a y-axis scale.  It should to make it easy to see what the actual values of the waveform is.

The spectrogram also needs axis labels.

**Comment by hoch** [comment]
Closing with 5326dc3a5745e84f0b2b13e9aa749d49375c4f6e. File a new issue for spectrogram though.

**Comment by rtoy** [comment]
Minor nit: I think the y-axis label would look better if you actually included 1 (-1) on the axis.  Perhaps I'm picky, but I hate graphs that don't have labels for the top (bottom) line.

**Comment by hoch** [comment]
Yes, I am aware of this issue. Will reopen this and let me fix the issue.

Also currently y-axis label is being drawn on top of the waveform. The waveform image should be pushed to the right for a couple of pixels.

**Comment by hoch** [comment]
Closing with 3cef6e2f0642f29a2adca616e7391ab68abd45c0.
