### ISSUE TITLE
Enhancement: Allow selectable number of channels

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#18]
Looks like the context always has two channels.

It would be nice to be able to select the number of channels.  I guess this also means making the waveform display include a display for each channel.

**Comment by hoch** [comment]
I will work on this issue along with #15. The current modular structure of waveform renderer makes this easy to do.

**Comment by hoch** [comment]
Closing with a57b9c52c2730cc17b2b9cac83a8fb92c28c326f.
