### ISSUE TITLE
Add a new line after comment

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#19]
The comment in the code window doesn't have a new line so it's really hard to notice that the cursor is at the end of the comment.

There should be a new line there so that when you start typing, it's not at the end of the comment.

**Comment by hoch** [comment]
Ah. Good point. This is an easy fix.

**Comment by hoch** [comment]
Fixed by a57b9c52c2730cc17b2b9cac83a8fb92c28c326f.
