### ISSUE TITLE
Gist pullout isn't discoverable

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#20]
Unless someone tells you or you do it by accident, it's impossible to know that you can grab the left edge of the code window and drag it to the right to get a pullout with the various gist snippets.

There should be something somewhere to make it discoverable.  Perhaps a small icon on the left, or maybe even a menu button to allow users to open it (and maybe configure other things).

**Comment by hoch** [comment]
Oh, you can press the menu button (three horizontal lines) right next to the title but I guess it isn't really noticeable. I will think of something better.

**Comment by rtoy** [comment]
Oh, the menu is already there. For some reason I just thought it was part of the Canopy title and didn't think it was clickable.

**Comment by hoch** [comment]
I am going to add some tutorial tool tips when the page opens.

**Comment by hoch** [comment]
Closing with a57b9c52c2730cc17b2b9cac83a8fb92c28c326f.
