### ISSUE TITLE
Error window doesn't get updated

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#23]
In a new instance, type something like

```
x = a
```

and press run.  You get an error message.  That's good.

Now fix up the code and enter something like 

```
x = 42
```

and press run.  This runs, and there should be no error, but the error window contains the error message from last time.

I think every press of run should clear out the window.

**Comment by hoch** [comment]
The log window is barely functional at the moment. (actually it is sort of a placeholder now.)

**Comment by rtoy** [comment]
That explains everything.  Is it possible not to have it do anything at all and have the messages go to the actual console?  I think it's existence with logs in it is rather confusing.

**Comment by hoch** [comment]
There needs to be a way of reporting errors from user-written JS code. I will find a better way to do this.

**Comment by hoch** [comment]
Closing with 5326dc3a5745e84f0b2b13e9aa749d49375c4f6e. The log pane has been removed. Will file another issue for another error reporting method.
