### ISSUE TITLE
Replay audio

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#31]
Currently when you press the render button, the audio is rendered and played out. That works fine.

But if you want to listen again, you can't.  The render button does nothing. You have to edit the code before the render button will re-render the example again. 

It would be good to either allow the render button to re-render and play the audio, or, better yet, just replay the audio if the code hasn't changed.

**Comment by hoch** [comment]
As a long term solution, I am thinking of changing the right pane (viewer area) to a scrollable workspace. You will be creating a new inspector (waveform, spectrogram or audio graph) whenever you render after the code changes. In short, each waveform inspector will have an individual playback button.

But for the short term, I can add a replay button at the top of the code editor.

I have to try it to see if this is the right UI pattern, and feel free to throw ideas if you have any.

**Comment by hoch** [comment]
Closing with 3cef6e2f0642f29a2adca616e7391ab68abd45c0.
