### ISSUE TITLE
Clipping of audio on playback

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#32]
Since an offline context has no restrictions on amplitude of the output, we can do pretty much whatever we want.  However, when the audio is played out (I presume with webaudio), the output does clip the signal.  Hence, what is displayed isn't really quite what is heard.

Perhaps it would be nice to pop up a warning (or some other less intrusive indicator) that there might be clipping when the audio is played.  However, I would not want the graphs or the generated data to have any clipping applied. It should be the actual full-range generated output, unclipped.

**Comment by hoch** [comment]
This is actually two issues:
1) Clip indicator along with the waveform - I've never seen such thing, so it has to be something new.)
2) Automatic y-axis scaling based on the maximum peak.

Currently I am thinking about the right UX pattern here.
