### ISSUE TITLE
Show some indication of the grab area where you can pull out the gists

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#33]
Since there is no indication of where the grab area for the gists are, I often accidentally pull it out when I try to mark out some of the code for copying or deleting.

There should be some kind of visual indicator of where that area is.  And also a small margin between that and the left side of the code area so that it's easier to highlight code regions.

**Comment by hoch** [comment]
This is interesting. Thanks so much for finding this bug.

How about getting rid of the panel-grab area? The menu button works fine anyway.

**Comment by rtoy** [comment]
Removing the panel-grab area is fine with me. It wasn't easy to discover anyway, except by accident.

**Comment by hoch** [comment]
Yes, I didn't know until you found that out. I think it's a part of Polymer's mobile UI.

**Comment by hoch** [comment]
Closing with 3cef6e2f0642f29a2adca616e7391ab68abd45c0.
