### ISSUE TITLE
Time axis labels should be formatted properly

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#34]
The time axis labels have funny values like 0:2267. For a 3-second context, I assume that really means 0.2267 sec.

Also, the right most label is 2:9 and is cutoff.  I assume there were more digits.  This also makes it difficult to tell if the end of the graph is really 3 and not 2.9xxx.

Bonus feature:  Have the labels actually go from 0 to 3, at least for the initial display.

**Comment by hoch** [comment]
The format of `min:sec:ms` is a sort of convention in the audio application. The proper formatting is needed for displaying the text.

This text and grid depend on the variable zoom level, so it would be a bit difficult to optimize them for specific cases. What I can do is configure the zoom level and grid units to display the better text.

**Comment by hoch** [comment]
Closing with 3cef6e2f0642f29a2adca616e7391ab68abd45c0.
