### ISSUE TITLE
Changing context variable breaks canopy

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#40]
If you do something stupid like

```
context = new OfflineAudioContext(...)
```

in the code snippet, canopy behaves badly. I currently get an error about maxPeak being undefined.

It would be useful if canopy could produce an error if the user changes the important context variable to something unexpected.

This is an unlikely scenario that I happened to run across because I was cutting and pasting some other code into canopy.

**Comment by hoch** [comment]
This issue is also moved to `spiral-code` component issue tracker.
https://github.com/hoch/spiral-coder/issues/1
