### ISSUE TITLE
Display current context settings

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#42]
Now that the snippet can control the settings of the context like the number of channels, duration, and sample rate, you don't have the settings window.  Since these all have some default, it would be nice to have some way to display the values.

**Comment by hoch** [comment]
Good point. The question is how and where.

**Comment by rtoy** [comment]
Pressing an info button that pops up a window with the info would work for me. 

The sample rate is really the only thing that isn't easily seen. The number of channels is pretty clear from how many graphs are shown, and the duration can be guessed at from the length of graphs.

**Comment by hoch** [comment]
Okay. SGTM.

**Comment by hoch** [comment]
Closing with fd88fb4. If you render anything, the lower left corner of the editor will display the info about the buffer.
