### ISSUE TITLE
Default snippet shouldn't call stop

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#54]
The default snippet has this:

```
osc.start();
osc.stop(1.0);
```

I don't think it should call stop.  While playing around with default snippet, I changed the duration to 2 sec and couldn't figure out why there was no output after 1 sec.  Until I scrolled down and found the stop that I had forgotten about.

**Comment by hoch** [comment]
Yes, I noticed that. However, calling start/stop as a pair is generally a good practice for WebAudio. I do believe Canopy can be a educational tool, so I will have to think about what to do about this.

**Comment by rtoy** [comment]
It could be said I'm too lazy by recycling the default snippet, but I am glad that the default has 90% of the boilerplate I want for most of my testing.

I should use my own snippets instead of the default.

**Comment by hoch** [comment]
Closing with fd88fb4.
