### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by sonicviz** [hoch/canopy#58]
Hi! Great project! Found it reading the comments on WAAX (which is also excellent).

A couple of queries:
Is it possible to use AudioBufferSource or microphone input?
Is it possible to add some UI controls to the components to visually manipulate params?
(like http://webaudioplayground.appspot.com/# )
Any more detailed documentation on the way soon?

My use case is I think Canopy is also great for education and I'm thinking of using it for an course on Web Audio I'm putting together.

ty!

**Comment by hoch** [comment]
Thanks!

Canopy currently supports non-realtime mode only (based on OfflineAudioContext), so I am not sure how I can accommodate your request. I am thinking about creating a real-time version of Canopy, but it's just an idea in the air for now.

I can certainly help with the documentation - what else needs to be done?

**Comment by sonicviz** [comment]
Thanks for the info.
