### ISSUE TITLE
Hard to control minimap controls

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#70]
Using the default code snippet, zoom in the graph to show the region from 0 to 0.05 sec or so.  Now try to grab the minimap control at the top to change the region that is displayed.  This is really hard.  No matter where I put the mouse to drag it, I end up shifting the start or end flags to a new time.  I want to move the whole window to a different location.  If the start and stop times are far enough apart, then I can place the mouse near the center of the area and drag the whole region around; this is what I want.  Only when the region is small does this not work.

**Comment by hoch** [comment]
I've thought about the UI pattern for this, but couldn't figure out what the best is. Do you have any suggestion?

Many DAWs have a minimum size constraint for the area that you can set. This is not suitable for Canopy's purpose. Perhaps Shfit + Wheel for moving the region?

**Comment by rtoy** [comment]
As we discussed, shift-drag on the flags would work out fine for my use case.

**Comment by hoch** [comment]
Alt+drag for moving a region without changing its size.

**Comment by hoch** [comment]
Alt+drag does not work well in linux. We are changing it to use the Shift key instead.
