### ISSUE TITLE
Zooming the audio graph scrolls the graph window

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#71]
Consider a code snippet that has 2 or more channels of output.  The graph window shows 2 or more graphs.  Now use the mouse and drag down to zoom in.  With enough zooming, the graph window will suddenly scroll down to show the last output channel.  This is annoying if you're trying to zoom in to see something on channel 0 and are suddenly shown channel n.

Would using, say, shift-mouse-scrollwheel to control zooming help with this?

**Comment by hoch** [comment]
Now Canopy supports shift-wheel zooming. (https://github.com/hoch/canopy/commit/1b06f4f01988bc6f902b4e70d27ca9bb75ac088b) Closing.
