### ISSUE TITLE
Keep zoom level when rendering

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#72]
Suppose I've loaded some code and have run it and I'm looking at the waveform graph.  I've zoomed into some desired time and amplitude zoom to examine the graph.

Now I tweak the code slightly and render again.  Currently, the waveform graph is zoomed out as normal.  But it would be very nice if the zoom level and position didn't actually change.  Then I can immediately examine what my change had on that region of the graph.  Without this, I have to drag and zoom around the graph to find the interesting region again.

**Comment by hoch** [comment]
What if your previous position is no longer valid in the new rendering? I've thought about this feature, but I couldn't decide what to do in this corner case.

**Comment by rtoy** [comment]
If the previous position is no longer valid, I'm fine if the graph zooms back out.  I think this is better than showing an empty graph (or whatever) because the region is invalid.
