### ISSUE TITLE
Option to display time axis in frames and/or render quanta

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#80]
The time axis is currently displayed in sec.  This is the most useful setting.

But on occasion it would be nice to have the time axis in frames.  Or maybe even render quanta.  Render quanta is kind of nice to make it clear where each processing block is (but does make graphing the data harder).

**Comment by hoch** [comment]
I have to think about the best way of doing this. If every RQ is drawn on the timeline, it's going to be messy.

**Comment by rtoy** [comment]
As discussed offline, this request is basically swapping out the axis in seconds to an axis with the frame number instead.  Should pretty much look the same as it does today, except for the labels.  The RQ shouldn't be any messier; the time units on the axis will just change.
