### ISSUE TITLE
Print fewer digits for sample value in tooltip

### ISSUE THREAD

**Issue by rtoy** [hoch/canopy#82]
After zooming in the graph to see the individual samples, place the mouse over one of the samples and look at the tooltip for the actual sample value.  It appears as if the actual sample value is printed as a double float value even though the output is a float.  This is normally ok, but if you have unstable filters, the output goes to infinity and you get numbers like 2.14643574308864d14 when the actual float value is 2.1464357e14.

Since the tooltip box has a nice size, the digits for the number get printed outside the box and are very hard to read.  The output should probably be limited to 7-8 significant digits.  Always printing the output in scientific notation would be acceptable to me.

**Comment by hoch** [comment]
Can you provide a repro code so I can test the implementation?
